(add-to-list 'load-path "~/.emacs.d/modes")
(autoload 'markdown-mode "markdown-mode" "Major mode for edting Markdown files" t)
(add-to-list 'auto-mode-alist '("\\.text\\'" . markdown-mode))
(add-to-list 'auto-mode-alist '("\\.markdown\\'" . markdown-mode))
(add-to-list 'auto-mode-alist '("\\.md\\'" . markdown-mode))
