(defun env-init-from-melpa ()
  (interactive)
  (package-refresh-contents)
  (package-install 'company)
  (package-install 'go-mode)
  (package-install 'haskell-mode)
  (package-install 'helm)
  (package-install 'markdown-mode)
  (package-install 'php-mode)
  (package-install 'projectile)
  ;;(package-install 'smex)
  (package-install 'sublime-themes)
  (package-install 'window-numbering)
  (package-install 'yasnippet)
  (package-install 'go-snippets)
  (package-install 'haskell-snippets)
  (package-install 'ycmd)
  (package-install 'company-ycmd)
  (package-install 'flycheck)
  (package-install 'flycheck-ycmd))

(provide 'env-init-from-melpa)
