(defun env-init-from-melpa ()
  (interactive)
  (package-refresh-contents)
  (unless (package-installed-p 'company)
    (package-install 'company))
  (unless (package-installed-p 'go-mode)
    (package-install 'go-mode))
  (unless (package-installed-p 'haskell-mode)
    (package-install 'haskell-mode))
  (unless (package-installed-p 'helm)
    (package-install 'helm))
  (unless (package-installed-p 'markdown-mode)
    (package-install 'markdown-mode))
  (unless (package-installed-p 'php-mode)
    (package-install 'php-mode))
  (unless (package-installed-p 'projectile)
    (package-install 'projectile))
  ;;(unless (package-installed-p 'smex)
  ;;  (package-install 'smex))
  (unless (package-installed-p 'sublime-themes)
    (package-install 'sublime-themes))
  (unless (package-installed-p 'material-theme)
    (package-install 'material-theme))
  (unless (package-installed-p 'window-numbering)
    (package-install 'window-numbering))
  (unless (package-installed-p 'yasnippet)
    (package-install 'yasnippet))
  (unless (package-installed-p 'go-snippets)
    (package-install 'go-snippets))
  (unless (package-installed-p 'haskell-snippets)
    (package-install 'haskell-snippets))
  (unless (package-installed-p 'ycmd)
    (package-install 'ycmd))
  (unless (package-installed-p 'company-ycmd)
    (package-install 'company-ycmd))
  (unless (package-installed-p 'flycheck)
    (package-install 'flycheck))
  (unless (package-installed-p 'flycheck-ycmd)
    (package-install 'flycheck-ycmd))
  (when (and (package-installed-p 'company) (package-installed-p 'haskell-mode))
    (package-install 'company-ghc)
    (package-install 'company-ghci))
  (unless (package-installed-p 'erlang)
    (package-install 'erlang)))

(provide 'env-init-from-melpa)
