(add-to-list 'load-path (expand-file-name "blog-admin" user-emacs-directory))
(unless (package-installed-p 'ctable)
  (package-install 'ctable))
(unless (package-installed-p 's)
  (package-install 's))
(unless (package-installed-p 'f)
  (package-install 'f))
(require 'blog-admin)
(provide 'init-blog-admin)
