(when (package-installed-p 'yasnippet)
  (unless (featurep 'yasnippet)
      (require 'yasnippet)
      )
  (yas-global-mode 1)
  (setq-default yas-prompt-functions '(yas-ido-prompt yas-dropdown-prompt))
  )
(provide 'init-yasnippet)
