(unless (package-installed-p 'ycmd)
  (package-install 'ycmd)
  )
(require 'ycmd)
;(add-hook 'after-init-hook #'global-ycmd-mode)
(set-variable 'ycmd-server-command '("/usr/local/bin/python" "/Users/toby/.emacs.d/ycmd/ycmd/"))
(add-hook 'c-mode-hook 'ycmd-mode)
(add-hook 'python-mode-hook 'ycmd-mode)
(add-hook 'c++-mode-hook 'ycmd-mode)
(add-hook 'php-mode-hook 'ycmd-mode)

(provide 'init-ycmd)
