(when (package-installed-p 'rust-mode)
  (when (package-installed-p 'company-racer)
    ; (setq racer-cmd "/usr/local/bin/racer")
    (unless (getenv "RUST_SRC_PATH")
      (cond ((string-equal system-type "darwin")
	     (setenv "RUST_SRC_PATH" (expand-file-name "~/Devel/src/rust/src")))
	    ((string-equal system-type "gnu/linux")
	     (setenv "RUST_SRC_PATH" (expand-file-name "~/src/rust/src")))))
    (require 'company-racer)
    (with-eval-after-load 'company
      (add-to-list 'company-backends 'company-racer))
    (when (package-installed-p 'racer)
      (add-hook 'rust-mode-hook
		'(lambda ()
		   (racer-mode)
		   (eldoc-mode)
		   (add-hook 'flycheck-mode-hook #'flycheck-rust-setup)
		   (local-set-key (kbd "M-.") #'racer-find-definition)
		   (local-set-key (kbd "TAB") #'company-indent-or-complete-common))))
  (when (package-installed-p 'rustfmt)
    (add-hook 'rust-mode-hook #'rustfmt-enable-on-save))))
(provide 'init-rust)
