;; check and install haskell-mode
(when (package-installed-p 'haskell-mode)
  (add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)
  (when (package-installed-p 'haskell-snippets)
    (require 'haskell-snippets)
    )
  (when (package-installed-p 'company-ghc)
;    (add-to-list 'company-backends 'company-ghc)
    )
  )
(provide 'init-haskell)
